### ISSUE TITLE
Center last line in WHStack horizontally

### ISSUE THREAD

**Issue by beeirl** [diegolavalledev/swiftuilib-wrap-stack#1]
Is there any possibility to center the last line of the WHStack horizontally?
Btw. thanks for sharing your work.

**Comment by diegolavalledev** [comment]
Thank you, this can be done by taking both vertical and horizontal alignments as arguments. Right now we only take vertical but we could do like `ZStack` and take both. The new horizontal alignment info goes straight into the frame modifier we already have in place for the individual horizontal stacks. It will be applied to all lines though, including the trailing line. I will try to make this change and release soon. Thanks again for your contribution.

**Comment by beeirl** [comment]
Thanks for getting back to me. I have forked it and made the changes you just described - can submit a PR if you want.

**Comment by diegolavalledev** [comment]
Awesome! Yeah or I can just merge it from your fork. Thanks 😊

**Comment by beeirl** [comment]
Yeah, just have to push my changes (still having them locally atm) - will do in the next hour
